// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1c5bf0hSCouXvBJxB79H_GlEbJ0mUy_w',
    appId: '1:1067679902700:web:1fd66d20d2716384bfaec9',
    messagingSenderId: '1067679902700',
    projectId: 'chatbuddy-4f108',
    authDomain: 'chatbuddy-4f108.firebaseapp.com',
    storageBucket: 'chatbuddy-4f108.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFqViubMZV2jNU4E27Ec2I8tDvT4JJsWQ',
    appId: '1:1067679902700:android:da3b390d99c7edf7bfaec9',
    messagingSenderId: '1067679902700',
    projectId: 'chatbuddy-4f108',
    storageBucket: 'chatbuddy-4f108.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN-mI3AyQSpxVLyA_QYjCVNE1Y8I7t1KA',
    appId: '1:1067679902700:ios:7622edbc100517cabfaec9',
    messagingSenderId: '1067679902700',
    projectId: 'chatbuddy-4f108',
    storageBucket: 'chatbuddy-4f108.appspot.com',
    iosBundleId: 'com.example.chatBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN-mI3AyQSpxVLyA_QYjCVNE1Y8I7t1KA',
    appId: '1:1067679902700:ios:b6373dec1ca71f10bfaec9',
    messagingSenderId: '1067679902700',
    projectId: 'chatbuddy-4f108',
    storageBucket: 'chatbuddy-4f108.appspot.com',
    iosBundleId: 'com.example.chatBuddy.RunnerTests',
  );
}
